language: node_js
node_js:
  - '4.2'

env:
  global:
  - secure: NyP/E5yVP5oUOWkuG5HwcyMqmAhV7IKIqU82lcd9+PGXjxD9MZmAfG1dO/qHjK5XW79PNGczDIISObHd0bkafvUBvzKByFVdP8poxdP/vn2ZDSrXLYJS/lwNF1LTz/foLpOX2MdLkdUVtqjVgBLCWmrQQcGMCM1WlFQI7qGSUBk3dTEBfaiVrbUPliCCUUpawvwDMEk+3LMU8kh/4ZwjJj9oVvFRztatVvobwhp+fDrIWBPK5pMZxyerT9RsNVpC52IBXogforkobuGaE8MsyGjwL4pUwwLGdEfTNWt0kU5XvYxLqHHAwCoBJABJwJ8VRSyLup4kg3RMRXV6chYgu840LSr7WjT8E1+svGMVhb/3IANJrJ/MOJeC6hVGwiG+s/MfCz2t+89284PC/liEHZ16ah/NBte5bhDG6tATd8rEwycJiqjcOFW5tONiN/FA8eaaNJF0n4ZcCfGCKaWVgNSMuj/WhgU13FZmIxBnmmhQPjA6TAkVqcIfOSXQDAcW51oHTc5PvGewB37K2EBSvtZ8lsodPspPFq62gfXEGy1KySIJFQY5VN6iO1Yd5ruLfpRjuRfm9VjAEq+FW+aT68zqE7usINeKA9TR8rZexWxXtkwWsDN0U090jctmMJSUZY70y3R8UbcZ9FKLWnIdVae3iVebiWzPNrvvYSEaMEM=
  - secure: HOONbqqVIV9N6il7xKLSZa4XKBGPjhjVETMeI09OgPfFvQb98kK6gD0RvZLP4Q4pA0TE0KB6K20e4XKy/k7MtoR1ADB1yTjNSs2DjYsiM12Mby4xoB5CT97vkfSp+ZOIvOsB1n4Wk/QeaPjwT4kevPsmdvL8SavBvAtd8N6N+UMFR/Mt9p+tBax1lPeVCrsb21Y64VHhJKxo2zYBDWJ4yfeWyYBf/7ZEgx6z+Aff2LAECi8eSOkpec+xIpXLE1iVg/FneJaPZ1+p5oLnoHH6MwoPqdn3uAhu5PjixybWU9e+7qvG3TyM7QGHdBNpJ6y+neqfbWqf1KaoPFA36DV8xahkd32tSOjxXC57XEyT3Wl+97AHbCsM/1eDGAJZz++dJdLhoKHrnDhfYQassGKQb/i/Mdn96aBbcYahDMpnNami1GZWvqA0wEny3CCre/47zZV5AgL4tZM/g0EBGpXnQvTIwKWvUat81eq1XXzvaBuBhWTkzuEpcmW/lN5ARtWRea3iMCr3/vNgAcR0n0Rju+Wg8njlnlsGc65fMfPc59OZAE2NCbeP0qgs3OiuNoIWNMrxdF6vA7MQLBqVAdMuPdJbS2jnn1gObg65nZZp73vMcj+Yt93H3ElM3wgNNnzGdvIJpsBrT5BfpMF922LcdFZQ9kRy+O6++ZyBNM3vaXQ=
  - secure: UHAZaq1pDNwtmyMEJgJDsWUAMtRKOV9LiLsbFaxJQYn0LsB9BRXOOJsm3J5DAtxItJWMdkz6aRYJSZ9VAi6xn/nQVu3Htfv4aaUPiqWqLtQ35GDofByAD5Sp/QeqwVY1kGaZQ89cekQtzaHqAP+uMc4nwAEq1+MgvI0BwUU0TTs7L1L1C/kgvvv6/bl6Mk9r5ObCaD2LN6lMLb6DQ9Av2vfrIv/z4C1idNMPo8CYkB3MViEB5QbkbMWNuoBjnYOSN7iyrX1B//kfp/zBwJAKWPRlujFv31jn1/wWTZA+JtKQBnFckNkIzGtxrq3jvhrXh57KI48UkmqJvwu/qfL4bHrpGxnw9ptHbFXQYq+rL3dATAt/skloEe//M6X1H++IGqWRnOS484UUtPpLwYjXuw8EUU1FRZPbk/2Am5HNo+tMUt1Ez9kWiwsEp6QHa4zmPRqXDJQW+zbIyfo42VJTe16ewOsyQZaRGbUv1eqNV2rj5w7vPv+xG96nZ3jjQ3ybeAEHFkPUMMzEK4tMDf0W21f9wSeee7Xibp19gwQYfS8t7MPrUx6qE+Or5cDJDR4ATWjVu/BHJaRNhBtE+Oif+k3K5qXUkeZPCyK1LuqBbZqEuQzqte7M5B+34DKByOAqlH1aq0NJhkm6dzKoayzAYR7lSvzHGNRgAcfcxFaH/DI=

before_deploy:
  - sudo pip install awscli

deploy:
  provider: script
  script: scripts/deploy.sh
  on:
    tags: true
